"""fixed type of date

Revision ID: 0915f21703fd
Revises: 9d82bd1b25e8
Create Date: 2024-06-04 18:32:33.667036

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '0915f21703fd'
down_revision: Union[str, None] = '9d82bd1b25e8'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('rolls', 'date_added',
               existing_type=postgresql.TIMESTAMP(),
               type_=sqlalchemy_utc.sqltypes.UtcDateTime(timezone=True),
               existing_nullable=False)
    op.alter_column('rolls', 'date_removed',
               existing_type=postgresql.TIMESTAMP(),
               type_=sqlalchemy_utc.sqltypes.UtcDateTime(timezone=True),
               existing_nullable=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('rolls', 'date_removed',
               existing_type=sqlalchemy_utc.sqltypes.UtcDateTime(timezone=True),
               type_=postgresql.TIMESTAMP(),
               existing_nullable=True)
    op.alter_column('rolls', 'date_added',
               existing_type=sqlalchemy_utc.sqltypes.UtcDateTime(timezone=True),
               type_=postgresql.TIMESTAMP(),
               existing_nullable=False)
    # ### end Alembic commands ###
